package com.example.rentagro.dao;

import com.example.rentagro.model.Maquina;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class MaquinaDAO {

    public List<Maquina> lista() {
        List<Maquina> maquinas = new ArrayList<>(Arrays.asList(
                new Maquina("Tratores",
                        "trator",
                        "Anuncio: 2 dias",
                        "R$ 250.00",
                        "(14)123456",
                        "Pompeia"),
                        new Maquina("Caminhões",
                        "caminhao",
                        "Anuncio: 3 dias",
                        "R$ 760.00",
                        "(14)654123",
                        "Marilia"),
                new Maquina("Plantadeira",
                        "colheitadeira1",
                        "Anuncio: 4 dias",
                        "R$ 230.00",
                        "(14)987456",
                        "Pompeia"),
                new Maquina("Colhedeira",
                        "colheitadeira",
                        "Anuncio: 6 dias",
                        "R$ 478.98",
                        "(14)123456",
                        "Tupã"),
                new Maquina("Implemento",
                        "implementos",
                        "Anuncio: 5 dias",
                        "R$ 899.99",
                        "(14)369852",
                        "Bastos"),
                new Maquina("Implemento",
                        "arado2",
                        "Anuncio: 2 dias",
                        "R$ 99.99",
                        "(14)987564",
                        "Garça"),
                new Maquina("Caminhão",
                        "caminhao3",
                        "Anuncio: 10 dias",
                        "R$ 450.00",
                        "(14)123456",
                        "Pompeia"),
                new Maquina("Caminhão",
                        "caminhao4",
                        "Anuncio: 10 dias",
                        "R$ 450.00",
                        "(14)963258",
                        "Pompeia"),
                new Maquina("Plantadeira",
                        "plantadeira3",
                        "Anuncio: 2 dias",
                        "R$ 980.00",
                        "(14)963258",
                        "Pompeia"),
                new Maquina("Plantadeira",
                        "plantadeira4",
                        "Anuncio: 2 dias",
                        "R$ 980.00",
                        "(14)963258",
                        "Pompeia"),
                new Maquina("Plantadeira",
                        "plantadeira5",
                        "Anuncio: 2 dias",
                        "R$ 980.00",
                        "(14)963258",
                        "Pompeia"),
                new Maquina("Trator",
                        "trator3",
                        "Anuncio: 14 dias",
                        "R$ 580.00",
                        "(14)963258",
                        "Quintana"),
                new Maquina("Trator",
                        "trator4",
                        "Anuncio: 14 dias",
                        "R$ 580.00",
                        "(14)963258",
                        "Quintana"),
                new Maquina("Trator",
                        "trator5",
                        "Anuncio: 14 dias",
                        "R$ 600.00",
                        "(14)963258",
                        "Adamantina"),
                new Maquina("Trator",
                        "trator4",
                        "Anuncio: 14 dias",
                        "R$ 580.00",
                        "(14)963258",
                        "Rancharia"),
                new Maquina("Trator",
                        "trator5",
                        "Anuncio: 14 dias",
                        "R$ 580.00",
                        "(14)963258",
                        "Pompeia"),
                new Maquina("Trator",
                        "trator6",
                        "Anuncio: 1 dia",
                        "R$ 500.00",
                        "(14)963258",
                        "Tupã"),
                new Maquina("Trator",
                        "trator7",
                        "Anuncio: 14 dias",
                        "R$ 600.00",
                        "(14)963258",
                        "Tupã"),
                new Maquina("Arado",
                        "arado",
                        "Anuncio: 1 dia",
                        "R$ 987.47",
                        "(14)123456",
                        "Adamantina")));
        return maquinas;
    }

}

